#!/data/data/com.termux/files/usr/bin/bash

pkg install -y clang cmake curl p7zip python

mkdir cazlha
pushd cazlha
curl https://www.ticalc.org/pub/amiga/caz.lha --output caz.lha

7z x caz.lha
cd caz/src

sed -i 's/dcc/clang/' makefile
make caz
chmod a+x caz
cp caz ../../../caz
cd -

popd
rm -rf cazlha/

# Placeholder to set up a place where all SOS libraries are cached

touch ~/.bashrc
path_addon='export PATH=$PATH:'"$PWD"
grep a-ti-den ~/.bashrc
if [ "$?" -eq 0 ]; then
    sed -i "s|^.*a-ti-den.*\$|$path_addon|" ~/.bashrc
else
    echo $path_addon>>~/.bashrc
fi
