#!/data/data/com.termux/files/usr/bin/python
#
# Script to split 83g files into 83p files in order to load them into TiLem
#

# Note that all 2 byte sizes are LSB MSB
#
# File format:
# 8 bytes: "**TI83**"
# 3 bytes: 26, 10, 0
# 42 bytes: Free text comment
# 2 bytes: Length of data section (File size - 57)
# n bytes: Data section...
# 2 bytes: Checksum (sum of bytes in data section %65536)
#
# Data section:
# 2 bytes: 11, 0
# 2 bytes: Length of variable data.
# 1 byte: Variable type (5 or 6 for programs)
# 8 bytes: Variable name
# 2 bytes: Length of variable data.
# n bytes: Variable data

import sys

def writeHeader(file):
    file.write(b'**TI83**')
    file.write(chr(26))
    file.write(chr(10))
    file.write(chr(0))
    file.write(b'123456789012345678901234567890123456789012')

fileName = sys.argv[1]
file = open(fileName, 'rb')
header = file.read(53)
dataSizeBytes = file.read(2)
dataSize = ord(dataSizeBytes[1]) * 256 + ord(dataSizeBytes[0])

dataSection = file.read(dataSize)

file.close()

while len(dataSection) >= (ord(dataSection[2]) + ord(dataSection[3])*256):
    newFile = open(dataSection[5:13].replace(chr(0),b'')+b'.83p', 'wb')
    writeHeader(newFile)
    dataLength = ord(dataSection[2]) + ord(dataSection[3])*256 + 15 # 15 is the amount of bytes of header information
    newFile.write(chr(dataLength%256))
    newFile.write(chr(dataLength/256))
    newFile.write(dataSection[0:dataLength])

    newDataSect = dataSection[0:dataLength]
    sum = 0
    for byte in newDataSect:
        sum = ord(byte) + sum
    checksum = sum % 65536

    newFile.write(chr(checksum%256))
    newFile.write(chr(checksum/256))

    newFile.close()
    dataSection = dataSection[dataLength:]
