#!/data/data/com.termux/files/usr/bin/python

# Script that downloads given URL
# unzips and loads 83p files to AndieGraph

import glob
import os
import sys

os.system('mkdir -p /data/data/com.termux/files/home/ti-stuff/downloads')
os.chdir('/data/data/com.termux/files/home/ti-stuff/downloads/')
os.system('rm *')
os.system('curl --output dl.zip ' + sys.argv[1])
os.system('unzip dl.zip')

group_files = glob.glob(os.getcwd() + '/*.83g')
group_files.extend(glob.glob(os.getcwd() + '/*.83G'))

for group_file in group_files:
    os.system('split83g ' + group_file)

prog_files = glob.glob(os.getcwd() + '/*.83p')
prog_files.extend(glob.glob(os.getcwd() + '/*.83P'))

print('almosttx --parent ~/ti-stuff/clean.ram --child /sdcard/Download/Ti83.RAM ' + ' '.join(prog_files))
os.system('almosttx --parent ~/ti-stuff/clean.ram --child /sdcard/Download/Ti83.RAM ' + ' '.join(prog_files))

os.system('startTI')
