#!/data/data/com.termux/files/usr/bin/python

# Script that downloads given URL
# unzips and loads 83p files to AndieGraph

import glob
import os
import sys

os.system('mkdir -p /data/data/com.termux/files/home/ti-stuff/downloads')
os.chdir('/data/data/com.termux/files/home/ti-stuff/downloads/')
os.system('rm -rf *')

shell = sys.argv[1].split('/')[-2]
shells = {'ashell' : 'https://www.ticalc.org/pub/83/asm/shells/ashell.zip',
          'doorscs' : 'https://www.ticalc.org/pub/83/asm/shells/dcs7.zip',
          'ion' : 'https://www.ticalc.org/pub/83/asm/shells/ion16u.zip',
          'sos' : 'https://www.ticalc.org/pub/83/asm/shells/sos.zip',
          'venus' : 'https://www.ticalc.org/pub/83/asm/shells/venus.zip'}

if shell in shells:
    os.system('curl --output shell.zip ' + shells[shell])
    os.system('unzip shell.zip')

os.system('curl --output dl.zip ' + sys.argv[1])
os.system('unzip dl.zip')

group_files = glob.glob(os.getcwd() + '/*.83g', recursive=True)
group_files.extend(glob.glob(os.getcwd() + '/**/*.83g', recursive=True))
group_files.extend(glob.glob(os.getcwd() + '/*.83G', recursive=True))
group_files.extend(glob.glob(os.getcwd() + '/**/*.83G', recursive=True))

for group_file in group_files:
    os.system('split83g ' + group_file)

prog_files = glob.glob(os.getcwd() + '/*.83p', recursive=True)
prog_files.extend(glob.glob(os.getcwd() + '/**/*.83p', recursive=True))
prog_files.extend(glob.glob(os.getcwd() + '/*.83P', recursive=True))
prog_files.extend(glob.glob(os.getcwd() + '/**/*.83P', recursive=True))

print('almosttx --parent ~/ti-stuff/clean.ram --child /sdcard/Download/Ti83.RAM "' + '" "'.join(prog_files) + '"')
os.system('almosttx --parent ~/ti-stuff/clean.ram --child /sdcard/Download/Ti83.RAM "' + '" "'.join(prog_files) + '"')

os.system('startTI')
